version: '3.8'

services:
  auth-service:
    container_name: connectfy-auth-service-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    depends_on:
      - mongo
      - postgres
    volumes:
      - .:/usr/src/app
    networks:
      - connectfy-core-network
      - connectfy-kafka-network
      - auth-db-network
    env_file:
      - .env.development
    ports:
      - "4000:4000"

  mongo:
    image: mongo:6
    container_name: connectfy-auth-mongo-dev
    volumes:
      - mongo-data:/data/db
    networks:
      - auth-db-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: authDb
    ports:
      - '25001:27017'

  postgres:
    image: postgres:15-alpine
    container_name: connectfy-auth-postgres-dev
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: authDb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - auth-db-network
    ports:
      - '5433:5432'

volumes:
  mongo-data:
  postgres-data:

networks:
  connectfy-core-network:
    external: true
  connectfy-kafka-network:
    external: true
  auth-db-network:
    external: true