version: '3.8'

services:
  auth-service:
    container_name: connectfy-auth-service-prod
    image: connectfy/connectfy-auth-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    depends_on:
      - mongo
    restart: always
    networks:
      - connectfy-auth-network
      - auth-db-network
      - connectfy-api-gateway-network
      - connectfy_kafka_network
    environment:
      - NODE_ENV=production
    env_file:
      - .env.production

  mongo:
    image: mongo:6.0
    container_name: connectfy-auth-mongo-prod
    volumes:
      - mongo-data:/data/db
    networks:
      - connectfy-auth-network
      - auth-db-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: authDb
    ports:
      - "25001:27017"

volumes:
  mongo-data:

networks:
  connectfy-auth-network:
    external: true
  auth-db-network:
  connectfy-api-gateway-network:
    external: true
  connectfy_kafka_network:
    external: true
