version: '3.8'

services:
  auth-service:
    container_name: connectfy-auth-service-dev
    image: connectfy/connectfy-auth-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app
    networks:
      - connectfy-auth-network
      - auth-db-network
      - connectfy-kafka-network
      - connectfy-api-gateway-network
    environment:
      - NODE_ENV=development
      - PORT=4000
      # - CHOKIDAR_USEPOLLING=true
      # - CHOKIDAR_INTERVAL=1000
      # - WATCHPACK_POLLING=true
    # command: npx nodemon --legacy-watch --watch src --ext ts,js,json --exec "npm run start:dev"
    env_file:
      - .env.development
    ports:
      - '4000:4000'

  mongo:
    image: mongo:6.0
    container_name: connectfy-auth-mongo-dev
    volumes:
      - mongo-data:/data/db
    networks:
      - connectfy-auth-network
      - auth-db-network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: authDb
    ports:
      - '25001:27017'

volumes:
  mongo-data:

networks:
  connectfy-auth-network:
    external: true
  auth-db-network:
  connectfy-kafka-network:
    external: true
  connectfy-api-gateway-network:
    external: true
