export enum ROLE {
  ADMIN = 'ADMIN',
  MODERATOR = 'MODERATOR',
  USER = 'USER',
}

export enum PROVIDER {
  PASSWORD = 'PASSWORD',
  GOOGLE = 'GOOGLE',
  FACEBOOK = 'FACEBOOK',
}

export enum USER_STATUS {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  DELETED = 'DELETED',
  BANNED = 'BANNED',
}

export enum GENDER {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  OTHER = 'OTHER',
}

export enum TOKEN_TYPE {
  PASSWORD_RESET = 'PASSWORD_RESET',
  DELETE_ACCOUNT = 'DELETE_ACCOUNT',
  RESTORE_ACCOUNT = 'RESTORE_ACCOUNT',
  CHANGE_USERNAME = 'CHANGE_USERNAME',
  CHANGE_EMAIL = 'CHANGE_EMAIL',
  CHANGE_PASSWORD = 'CHANGE_PASSWORD',
  CHANGE_PHONE_NUMBER = 'CHANGE_PHONE_NUMBER',
  DEACTIVATE_ACCOUNT = 'DEACTIVATE_ACCOUNT',
}

export enum PHONE_NUMBER_ACTION {
  UPDATE = 'UPDATE',
  REMOVE = 'REMOVE',
}

export enum IDENTIFIER_TYPE {
  USERNAME = 'USERNAME',
  EMAIL = 'EMAIL',
  PHONE_NUMBER = 'PHONE_NUMBER',
  FACE_DESCRIPTOR = 'FACE_DESCRIPTOR',
}

export enum GOOGLE_AUTH_LOGIN_TYPE {
  LOGIN = 'LOGIN',
  SIGNUP = 'SIGNUP',
}

export enum FORGOT_PASSWORD_IDENTIFIER_TYPE {
  EMAIL = 'EMAIL',
  PHONE_NUMBER = 'PHONE_NUMBER',
}

export enum LANGUAGE {
  EN = 'en',
  AZ = 'az',
  RU = 'ru',
  TR = 'tr',
}

export enum THEME {
  DARK = 'dark',
  LIGHT = 'light',
  DEVICE = 'device',
}

export enum STARTUP_PAGE {
  MESSENGER = 'MESSENGER',
  GROUPS = 'GROUPS',
  CHANNELS = 'CHANNELS',
  USERS = 'USERS',
  NOTIFICATION = 'NOTIFICATION',
  PROFILE = 'PROFILE',
}

export enum TIME_FORMAT {
  H24 = '24h',
  H12 = '12h',
}

export enum DATE_FORMAT {
  DDMMYYYY = 'DD/MM/YYYY',
  MMDDYYYY = 'MM/DD/YYYY',
}

export enum NOTIFICATION_SOUND_MODE {
  SOUND = 'SOUND',
  SILENT = 'SILENT',
  DND = 'DND',
}

export enum NOTIFICATION_CONTENT_MODE {
  HEADER_AND_CONTENT = 'HEADER_AND_CONTENT',
  HEADER_ONLY = 'HEADER_ONLY',
  HIDE_NOTIFICATION = 'HIDE_NOTIFICATION',
}

export enum PRIVACY_SETTINGS_CHOICE {
  EVERYONE = 'EVERYONE',
  MY_FRIENDS = 'MY_FRIENDS',
  NOBODY = 'NOBODY',
}

export enum DELETE_REASON {
  USER_REQUEST = 'USER_REQUEST',
  TERMS_VIOLATION = 'TERMS_VIOLATION',
  SPAM = 'SPAM',
  FRAUD = 'FRAUD',
  SECURITY = 'SECURITY',
  INACTIVITY = 'INACTIVITY',
  ADMIN_ACTION = 'ADMIN_ACTION',
  OTHER = 'OTHER',
}

export enum DEVICE_TYPE {
  WEB = 'WEB',
  MOBILE = 'MOBILE',
  TABLET = 'TABLET',
  DESKTOP = 'DESKTOP',
  UNKNOWN = 'UNKNOWN',
}

export enum BROWSER_TYPE {
  CHROME = 'CHROME',
  FIREFOX = 'FIREFOX',
  SAFARI = 'SAFARI',
  EDGE = 'EDGE',
  OPERA = 'OPERA',
  BRAVE = 'BRAVE',
  SAMSUNG = 'SAMSUNG',
  UNKNOWN = 'UNKNOWN',
}

export enum OS_TYPE {
  WINDOWS = 'WINDOWS',
  MACOS = 'MACOS',
  LINUX = 'LINUX',
  ANDROID = 'ANDROID',
  IOS = 'IOS',
  UNKNOWN = 'UNKNOWN',
}